# Generated by Django 2.2.14 on 2020-09-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bref',
            new_name='brief',
        ),
    ]
